### ISSUE TITLE
version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/AMDock#15]
AMDock
Traceback (most recent call last):
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/bin/AMDock", line 7, in <module>
    from AMDock.Docking_Program import run
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 9, in <module>
    from AMDock.result_tab import Results
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/AMDock/result_tab.py", line 9, in <module>
    from AMDock.variables import Variables
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/AMDock/variables.py", line 6, in <module>
    import AutoDockTools, pymol
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/pymol/__init__.py", line 558, in <module>
    import pymol._cmd
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/pymol/_cmd.cpython-39-x86_64-linux-gnu.so)

**Comment by marioernestovaldes** [comment]
this solves the issue:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
