### ISSUE TITLE
error in Running Prepare_Receptor4...

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/AMDock#16]
AMDOCK: Running Prepare_Receptor4 for Target...

set verbose to  True
set cleanup to  nphs_lps_waters_nonstdres_deleteAltB
Traceback (most recent call last):
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/AutoDockTools/Utilities24/prepare_receptor4.py", line 157, in <module>
    mols = Read(receptor_filename)
  File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/AMDock/lib/python3.9/site-packages/MolKit/__init__.py", line 38, in Read
    raise AssertionError("%s does't exist" % filename)
AssertionError: complex_min_h.pdb does't exist

**Comment by Valdes-Tresanco-MS** [comment]
Close via [cb668f0](https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3/commit/cb668f0c3a964097da36e80d54355f4e53b9181f)
