### ISSUE TITLE
New version unable to execute 

### ISSUE THREAD

**Issue by debanjansen48** [Valdes-Tresanco-MS/AMDock#17]
install grid_amdock.py with in Pymol plugin still bellow error persists 

Traceback (most recent call last):
  File "/home/debanjan/amber20/miniconda/bin/AMDock", line 5, in <module>
    from AMDock.Docking_Program import run
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 9, in <module>
    from AMDock.result_tab import Results
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/AMDock/result_tab.py", line 9, in <module>
    from AMDock.variables import Variables
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/AMDock/variables.py", line 6, in <module>
    import AutoDockTools, pymol
ModuleNotFoundError: No module named 'pymol'

**Comment by debanjansen48** [comment]
Ok...let me try
