### ISSUE TITLE
error with prepare_receptor4

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/AMDock#18]
i have a protein with some of the coordinates looks like this:
ATOM   5063  CG  LYS B 316     157.454-100.044  -4.756  0.0187 1.9080
as you notice the X and Y coordinates are not separated by space. when i tried to run the prepare_receptor4 in AMDock it produced this error:

```
Traceback (most recent call `last):
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/pdbParser.py", line 433, in parse_PDB_atoms
    at = self.parse_PDB_ATOM_record(atRec, mol)
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/pdbParser.py", line 1375, in parse_PDB_ATOM_record
    atom._coords = [[float(rec[5]), float(rec[6]), float(rec[7])]]
ValueError: could not convert string to float: '157.454-100.044'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/command_runner.py", line 64, in run
    result = self.fn(*self.args)
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/tools.py", line 499, in __init__
    self.pqr = Read(pqr_file)[0]
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/__init__.py", line 74, in Read
    molecules = parser.parse()
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/pdbParser.py", line 653, in parse
    self.pdbRecordParser[record](self.allLines, self.mol)
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/pdbParser.py", line 437, in parse_PDB_atoms
    raise RuntimeError("Error parsing the following line in pdb:\n" + atRec)
RuntimeError: Error parsing the following line in pdb:
ATOM   5063  CG  LYS B 316     157.454-100.044  -4.756  0.0187 1.9080
set verbose to  True
set cleanup to  nphs_lps_waters_nonstdres_deleteAltB
Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/AutoDockTools/Utilities24/prepare_receptor4.py", line 157, in <module>
    mols = Read(receptor_filename)
  File "/home/ibrahim/anaconda3/envs/AMDock/lib/python3.9/site-packages/MolKit/__init__.py", line 38, in Read
    raise AssertionError("%s does't exist" % filename)
AssertionError: HIF_pymol_h.pdb does't exist
```

**Comment by RashedCh** [comment]
>Linux 64-bit Ubuntu 20.04> Autodock Vina > "Prepare input" returns the following error:
Unhandled Python exception
Aborted (core dumped)

**Comment by Valdes-Tresanco-MS** [comment]
@RashedCh I need more information. Can you attach an image of the program log where I can see the error?

**Comment by RashedCh** [comment]
Hi Mario,
thanks for getting back to me.

Here's what I tried -
[image: image.png]

When I "Prepare Input", the program crashes with the following error msg:

[image: image.png]

Best,
Rashed

**Comment by RashedCh** [comment]
Sorry, I don't see any "program log" in /var/log ..

**Comment by Valdes-Tresanco-MS** [comment]
Please upload the images again because they are not visible. 
The program log is shown on the right side.

**Comment by RashedCh** [comment]
The program closes down completely leaving an error the following error on the terminal
![image](https://user-images.githubusercontent.com/63067518/174466471-e372c747-9c81-4eda-9022-6ce6ee305a50.png)

**Comment by Valdes-Tresanco-MS** [comment]
fixed via https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3/commit/aee55d50d5bdcfdbcd80220499df8cde2a8f4b2a
Please, update AutoDockTools: 
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3 -U
```
