### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by shrijoshi20** [Valdes-Tresanco-MS/AMDock#25]
i tried to install AMDock using the given method but getting following errors

(base) shrikant@shrikant-HP:~$ amdock 
Traceback (most recent call last):
  File "/home/shrikant/miniconda3/envs/AMDock/bin/AMDock", line 5, in <module>
    from AMDock.Docking_Program import run
  File "/home/shrikant/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 9, in <module>
    from AMDock.result_tab import Results
  File "/home/shrikant/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/result_tab.py", line 9, in <module>
    from AMDock.variables import Variables
  File "/home/shrikant/miniconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/variables.py", line 6, in <module>
    import AutoDockTools, pymol
  File "/home/shrikant/miniconda3/envs/AMDock/lib/python3.9/site-packages/pymol/__init__.py", line 558, in <module>
    import pymol._cmd
ImportError: /home/shrikant/miniconda3/envs/AMDock/lib/python3.9/site-packages/pymol/../../../libnetcdf.so.19: undefined symbol: H5Pset_fapl_ros3

**Comment by Valdes-Tresanco-MS** [comment]
Please, show me the output of `conda list`

**Comment by shrijoshi20** [comment]
(base) shrikant@shrikant-HP:~$ conda list
# packages in environment at /home/shrikant/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
adblockparser             0.7                      pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
automat                   22.10.0                  pypi_0    pypi
boltons                   23.0.0           py38h06a4308_0  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.5.7         py38h06a4308_0  
cffi                      1.15.1           py38h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     23.5.2           py38h06a4308_0  
conda-content-trust       0.1.3            py38h06a4308_0  
conda-libmamba-solver     23.5.0           py38h06a4308_0  
conda-package-handling    2.1.0            py38h06a4308_0  
conda-package-streaming   0.8.0            py38h06a4308_0  
constantly                15.1.0                   pypi_0    pypi
cryptography              39.0.1           py38h9ce1e76_2  
fmt                       9.1.0                hdb19cb5_0  
funcparserlib             1.0.1                    pypi_0    pypi
h2                        4.1.0                    pypi_0    pypi
hpack                     4.0.0                    pypi_0    pypi
hyperframe                6.0.1                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4              py38h06a4308_0  
incremental               22.10.0                  pypi_0    pypi
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
krb5                      1.20.1               h143b758_1  
ld_impl_linux-64          2.38                 h1181459_1  
libarchive                3.6.2                h6ac8c49_2  
libcurl                   8.1.1                h251f7ec_1  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libmamba                  1.4.1                h2dafd23_1  
libmambapy                1.4.1            py38h2dafd23_1  
libnghttp2                1.52.0               h2d74bed_1  
libsolv                   0.7.22               he621ea3_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libxml2                   2.10.3               hcbfbd50_0  
lz4-c                     1.9.4                h6a678d5_0  
ncurses                   6.4                  h6a678d5_0  
openssl                   3.0.9                h7f8727e_0  
packaging                 23.0             py38h06a4308_0  
pcre2                     10.37                he7ceb23_1  
pillow                    10.0.0                   pypi_0    pypi
pip                       23.1.2           py38h06a4308_0  
pluggy                    1.0.0            py38h06a4308_1  
priority                  1.3.0                    pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pybind11-abi              4                    hd3eb1b0_1  
pycosat                   0.6.4            py38h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py38h06a4308_0  
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.2                  pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.17               h955ad1f_0  
qt5reactor                0.6.3                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
reproc                    14.2.4               h295c915_1  
reproc-cpp                14.2.4               h295c915_1  
requests                  2.29.0           py38h06a4308_0  
ruamel.yaml               0.17.21          py38h5eee18b_0  
ruamel.yaml.clib          0.2.6            py38h5eee18b_1  
setuptools                67.8.0           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
splash                    3.5                      pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.0           py38h06a4308_0  
tqdm                      4.65.0           py38hb070fc8_0  
twisted                   22.10.0                  pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   1.26.16          py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
xvfbwrapper               0.2.9                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yaml-cpp                  0.7.0                h295c915_1  
zlib                      1.2.13               h5eee18b_0  
zope-interface            6.0                      pypi_0    pypi
zstandard                 0.19.0           py38h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by nayanmondal1337** [comment]
me too have similar issue. the output is

(base) nayan@nayan:~/Desktop$ conda list
# packages in environment at /home/nayan/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
amdock                    1.6.2                    pypi_0    pypi
autodocktools-py3         1.5.7.post1+9.gda0c87c          pypi_0    pypi
brotlipy                  0.7.0           py39h27cfd23_1003  
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
cffi                      1.14.6           py39h400218f_0  
chardet                   4.0.0           py39h06a4308_1003  
conda                     4.10.3           py39h06a4308_0  
conda-package-handling    1.7.3            py39h27cfd23_1  
cryptography              3.4.7            py39hd23ed53_0  
docutils                  0.17.1                   pypi_0    pypi
idna                      2.10               pyhd3eb1b0_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
mmcif-pdbx                2.0.1                    pypi_0    pypi
mpi4py                    3.1.4                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
numpy                     1.25.2                   pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
pdb2pqr                   3.6.1                    pypi_0    pypi
pip                       21.1.3           py39h06a4308_0  
propka                    3.5.0                    pypi_0    pypi
pycosat                   0.6.3            py39h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.2                  pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.5                h12debd9_4  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
ruamel_yaml               0.15.100         py39h27cfd23_0  
setuptools                52.0.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.61.2             pyhd3eb1b0_1  
tzdata                    2021a                h52ac0ba_0  
urllib3                   1.26.6             pyhd3eb1b0_1  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3

**Comment by shrijoshi20** [comment]
Kindly help me out in getting issue solved and install AMDock. Thanks.

**Comment by Valdes-Tresanco-MS** [comment]
I apologize for my delayed response. It seems like pymol changes. I will check what's going on and try to fix it ASAP.

**Comment by deepakshilkar** [comment]
Same error

`
Apps$ AMDock
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/AMDock/bin/AMDock", line 5, in <module>
    from AMDock.Docking_Program import run
  File "/home/user/anaconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 3, in <module>
    from AMDock.checker import Checker
  File "/home/user/anaconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/checker.py", line 1, in <module>
    from AMDock.warning import (prot_with_metal_warning, metal_no_ADzn_warning1,
  File "/home/user/anaconda3/envs/AMDock/lib/python3.9/site-packages/AMDock/warning.py", line 1, in <module>
    from PyQt5.QtWidgets import *
ImportError: /home/user/anaconda3/envs/AMDock/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
`
