### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nayanmondal1337** [Valdes-Tresanco-MS/AMDock#26]
I am using linuxmint and used pip to install but following errors are coming. How ever pymol is installed

AMDock 
Traceback (most recent call last):
  File "/home/nayan/miniconda3/bin/AMDock", line 5, in <module>
    from AMDock.Docking_Program import run
  File "/home/nayan/miniconda3/lib/python3.9/site-packages/AMDock/Docking_Program.py", line 9, in <module>
    from AMDock.result_tab import Results
  File "/home/nayan/miniconda3/lib/python3.9/site-packages/AMDock/result_tab.py", line 9, in <module>
    from AMDock.variables import Variables
  File "/home/nayan/miniconda3/lib/python3.9/site-packages/AMDock/variables.py", line 6, in <module>
    import AutoDockTools, pymol
ModuleNotFoundError: No module named 'pymol'

**Comment by Valdes-Tresanco-MS** [comment]
I apologize for my delayed response. It seems like pymol changes. I will check what's going on and try to fix it ASAP.
